import Link from 'next/link'
import { Calendar, Clock, ArrowLeft, Share2 } from 'lucide-react'
import { notFound } from 'next/navigation'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

// This will be replaced with actual API call later
async function getBlogPost(slug: string) {
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/api/posts/${slug}`, {
      cache: 'no-store'
    })
    if (!res.ok) return null
    return await res.json()
  } catch {
    return null
  }
}

function formatDate(dateString: string) {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

function getReadingTime(content: string) {
  const wordsPerMinute = 200
  const words = content.split(' ').length
  const minutes = Math.ceil(words / wordsPerMinute)
  return `${minutes} min read`
}

// Convert markdown-like content to HTML (basic implementation)
function formatContent(content: string) {
  return content
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')
    .replace(/^/, '<p>')
    .replace(/$/, '</p>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code class="bg-gray-800 px-2 py-1 rounded text-sm font-mono">$1</code>')
}

export default async function BlogPostPage({ params }: { params: { slug: string } }) {
  const post = await getBlogPost(params.slug)

  if (!post) {
    notFound()
  }

  const formattedContent = formatContent(post.content)

  return (
    <div className="min-h-screen bg-black text-white">
      <Navbar />
      
      {/* Back to Blog */}
      <div className="pt-20 pb-4 bg-black">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <Link
            href="/blog"
            className="inline-flex items-center text-neon-cyan hover:text-neon-green transition-colors font-mono text-sm"
          >
            <ArrowLeft className="mr-2 w-4 h-4" />
            &gt; Back to Blog
          </Link>
        </div>
      </div>

      {/* Article Header */}
      <article className="pb-16 bg-black">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <header className="mb-12">
            <div className="terminal-text text-sm mb-4">
              &gt; Loading article.id: {params.slug}
            </div>
            <h1 className="text-3xl md:text-5xl font-bold text-white mb-6 font-mono leading-tight">
              {post.title}
            </h1>
            
            <div className="flex flex-wrap items-center gap-6 text-sm text-gray-400 mb-8 font-mono">
              <div className="flex items-center">
                <Calendar className="w-4 h-4 mr-2 text-neon-cyan" />
                {formatDate(post.created_at)}
              </div>
              <div className="flex items-center">
                <Clock className="w-4 h-4 mr-2 text-neon-green" />
                {getReadingTime(post.content)}
              </div>
              <div className="flex items-center">
                <Share2 className="w-4 h-4 mr-2 text-neon-purple" />
                Topic: {post.topic}
              </div>
            </div>

            {post.keywords && post.keywords.length > 0 && (
              <div className="flex flex-wrap gap-2 mb-8">
                {post.keywords.map((keyword: string, i: number) => (
                  <span 
                    key={i} 
                    className="bg-neon-cyan/20 text-neon-cyan px-3 py-1 rounded text-sm font-mono"
                  >
                    {keyword}
                  </span>
                ))}
              </div>
            )}
          </header>

          {/* Article Content */}
          <div className="prose prose-invert prose-lg max-w-none">
            <div className="glass-effect p-8 rounded-lg neon-border">
              <div 
                className="text-gray-300 leading-relaxed"
                dangerouslySetInnerHTML={{ __html: formattedContent }}
              />
            </div>
          </div>

          {/* Article Footer */}
          <footer className="mt-12 pt-8 border-t border-neon-cyan/20">
            <div className="glass-effect p-6 rounded-lg">
              <div className="terminal-text text-xs mb-3">
                &gt; Article generated by KHIM-TECH AI Blog System
              </div>
              <p className="text-gray-300 text-sm mb-4">
                This article was automatically generated as part of our commitment to sharing 
                knowledge about data science, machine learning, and full-stack development.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <Link
                  href="/contact"
                  className="bg-gradient-to-r from-neon-cyan to-neon-green text-black px-6 py-3 rounded-lg font-semibold hover:shadow-lg hover:shadow-neon-cyan/50 transition-all duration-300 inline-flex items-center justify-center font-mono"
                >
                  &gt; Discuss This Article
                </Link>
                <Link
                  href="/blog"
                  className="border border-neon-cyan text-neon-cyan px-6 py-3 rounded-lg font-semibold hover:bg-neon-cyan/10 transition-all duration-300 font-mono neon-border inline-flex items-center justify-center"
                >
                  &gt; More Articles
                </Link>
              </div>
            </div>
          </footer>
        </div>
      </article>

      <Footer />
    </div>
  )
}

// This generates the possible paths at build time
export async function generateStaticParams() {
  // In a real implementation, this would fetch all blog post slugs
  // For now, return empty array since posts are dynamic
  return []
}